[project]
name = "tuspyserver-example-basic"
version = "4.0.0"
description = "Basic tuspyserver example using uvicorn; requires uv."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "tuspyserver>=4.0",
  "uvicorn>=0.34.2",
]

[tool.uv.sources]
tuspyserver = { workspace = true }
